name: Web Page Archive
type: module
description: 'Provides web page data archiving and reporting functionality.'
package: Web Page Archive
core: 8.x
configure: entity.web_page_archive.collection
dependencies:
  - drupal:web_page_archive
php: 7.0
